In [19]:
import numpy as np

# Forming a matrix A of dimensions 5x2 and a vector x of dimensions 2x1,
# both filled with random whole numbers between -100 to 100.
A = np.random.randint(-100, 100, size=(5, 2))
x = np.random.randint(-100, 100, size=(2, 1))

# Printing matrix A and vector x
print("Matrix A:")
print(A)
print("\nVector x:")
print(x)

# Calculating Ax
Ax = np.dot(A, x)
print("\nAx:")
print(Ax)

# Constructing a diagonal matrix B, with the elements [1,2,3,4,5] populating the diagonal.
B = np.diag([1, 2, 3 ,4 ,5])
print("\nMatrix B:")
print(B)

# Calculating BA
BA = np.dot(B,A)
print("\nBA:")
print(BA)


Matrix A:
[[ 63   3]
 [-88   6]
 [ 84 -61]
 [-78  86]
 [ 67  14]]

Vector x:
[[ 69]
 [-94]]

Ax:
[[  4065]
 [ -6636]
 [ 11530]
 [-13466]
 [  3307]]

Matrix B:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

BA:
[[  63    3]
 [-176   12]
 [ 252 -183]
 [-312  344]
 [ 335   70]]


In [20]:
# Calculating rank of A and B
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_BA = np.linalg.matrix_rank(BA)
print("\nThe rank of Matrix A is:", rank_A)
print("The rank of Matrix B is:", rank_B)
print("The rank of BA is:", rank_BA)


The rank of Matrix A is: 2
The rank of Matrix B is: 5
The rank of BA is: 2


In [25]:
import numpy as np

# Creating matrices A and B
A = np.array([[-2, 1, 8], [-1, -1, 7], [3, 0, 4]])
B = np.array([[5, 0, -7], [6, 3, -9], [-2, -2, 0]])
C = np.array([[6, 3, -1], [2, 4, 5], [-1, -1, 8]])
# Calculating AB
AB = np.dot(A, B)

# Calculating BA
BA = np.dot(B, A)

X = AB-BA
Y = np.dot(AB, C)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB-BA:\n", X)
print("\nABC:\n", Y)

Matrix A:
 [[-2  1  8]
 [-1 -1  7]
 [ 3  0  4]]

Matrix B:
 [[ 5  0 -7]
 [ 6  3 -9]
 [-2 -2  0]]

AB:
 [[-20 -13   5]
 [-25 -17  16]
 [  7  -8 -21]]

BA:
 [[-31   5  12]
 [-42   3  33]
 [  6   0 -30]]

AB-BA:
 [[ 11 -18  -7]
 [ 17 -20 -17]
 [  1  -8   9]]

ABC:
 [[-151 -117   -5]
 [-200 -159   68]
 [  47   10 -215]]


In [35]:
import numpy as np

# Define matrices A, B, C
A = np.array([[-2, 1, 8], [-1, -1, 7], [3, 0, 4]])
B = np.array([[5, 0, -7], [6, 3, -9], [-2, -2, 0]])
C = np.array([[6, 3, -1], [2, 4, 5], [-1, -1, 8]])

# Concatenate A, B, C into a 9x3 matrix D
D = np.concatenate((A, B, C))

# Create vector b
b = np.array([3, -10, 2]).reshape(-1, 1)

# Compute least squares solution
#x, residuals, rank, s = np.linalg.lstsq(D, b, rcond=None)

#print("The least squares solution is:\n", x)
print(D)
print("\nb:\n", b)

[[-2  1  8]
 [-1 -1  7]
 [ 3  0  4]
 [ 5  0 -7]
 [ 6  3 -9]
 [-2 -2  0]
 [ 6  3 -1]
 [ 2  4  5]
 [-1 -1  8]]

b:
 [[  3]
 [-10]
 [  2]]


In [36]:
from scipy.stats import norm

# mean and standard deviation
mu = 3
sigma = 0.8

# calculate the z-scores
z1 = (2.2 - mu) / sigma
z2 = (3.8 - mu) / sigma

# use the cumulative distribution function (CDF) to get the probabilities
p1 = norm.cdf(z1)
p2 = norm.cdf(z2)

# the probability of a value falling between 2.2 and 3.8 is the difference between the two probabilities
p = p2 - p1

print("The probability that a randomly selected college student drinks between 2.2 and 3.8 cups of coffee per day is", p)


The probability that a randomly selected college student drinks between 2.2 and 3.8 cups of coffee per day is 0.6826894921370859


In [39]:
import numpy as np

# Define matrices A, B, C
A = np.array([[-2, 1, 8],
              [-1, -1, 7],
              [3, 0, 4]])

B = np.array([[5, 0, -7],
              [6, 3, -9],
              [-2, -2, 0]])

C = np.array([[6, 3, -1],
              [2, 4, 5],
              [-1, -1, 8]])

# Concatenate matrices A, B, C to create matrix D
D = np.concatenate((A, B, C), axis=1)

# Display matrix D
print("Matrix D:")
print(D)

# Create vector b
b = np.array([3, -10, 2])

# Find the least squares solution x that minimizes ||D^T x - b||^2
x_least_squares = np.linalg.lstsq(D, b, rcond=None)[0]

# Display the result
print("\nLeast squares solution x:")
print(x_least_squares)

Matrix D:
[[-2  1  8  5  0 -7  6  3 -1]
 [-1 -1  7  6  3 -9  2  4  5]
 [ 3  0  4 -2 -2  0 -1 -1  8]]

Least squares solution x:
[ 0.15053282  0.49890198  0.68400043 -0.56288901 -1.02020685  0.58207024
  0.8280899  -0.41396702 -0.49245863]


In [51]:
import numpy as np
from scipy import stats

# Prices
prices = np.array([999, 1499, 1997, 398, 591, 498, 798, 849, 449, 348])

# Sample mean (average)
mean = np.mean(prices)

# Sample standard deviation
std_dev = np.std(prices, ddof=1)  # ddof=1 for sample standard deviation

# Sample size
n = len(prices)

# Z-score for 95% confidence
z = stats.norm.ppf(0.975)  # two-tailed 95% confidence

# Margin of error
margin_of_error = z * (std_dev / np.sqrt(n))

# Confidence interval
conf_interval = (mean - margin_of_error, mean + margin_of_error)

print("The 95% confidence interval for the true mean price is", conf_interval)


The 95% confidence interval for the true mean price is (511.4451904629338, 1173.7548095370662)


In [52]:
import numpy as np
from scipy import stats

# Given values
x_bar = 13.4  # sample mean
mu = 12  # population mean
sigma = 4.5  # population standard deviation
n = 50  # sample size
alpha = 0.01  # significance level

# Calculate the test statistic (z-score)
z = (x_bar - mu) / (sigma / np.sqrt(n))

# Calculate the critical z-value for a two-tailed test
z_critical = stats.norm.ppf(1 - alpha/2)

# Check if we should reject the null hypothesis
if np.abs(z) > np.abs(z_critical):
    print("Reject the null hypothesis")
else:
    print("Do not reject the null hypothesis")


Do not reject the null hypothesis


In [53]:
import numpy as np
from scipy import stats

# Grades
grades = np.array([92.3, 89.4, 76.9, 65.2, 49.1, 96.7, 69.5, 72.8, 67.5, 52.8, 88.5, 79.2, 72.9, 68.7, 75.8])

# Sample variance
s_squared = np.var(grades, ddof=1)  # ddof=1 for sample variance

# Sample size
n = len(grades)

# Population variance under H0
sigma_squared = 100

# Calculate the test statistic (chi-square)
chi_squared = (n - 1) * s_squared / sigma_squared

# Calculate the critical chi-square value for alpha = 0.05 with n - 1 degrees of freedom
chi_squared_critical = stats.chi2.ppf(1 - 0.05, df=n - 1)

# Check if we should reject the null hypothesis
if chi_squared > chi_squared_critical:
    print("Reject the null hypothesis")
else:
    print("Do not reject the null hypothesis")


Reject the null hypothesis
